language: node_js

node_js:
  - '10'
  - '8'
  - '6'

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn unit

before_deploy:
  - yarn build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: 'dist'
  on:
    branch: master
